Fix 2.2.0 build failure when management interface disabled
I just upgraded to 2.2.0, and my build fails with:

ps.c: In function 'port_share_open':
ps.c:778:7: error: 'management' undeclared (first use in this function)
ps.c:778:7: note: each undeclared identifier is reported only once for
each function it appears in
make[5]: *** [ps.o] Error 1

[Comment by David Sommerseth:
 This happens only when building with --enable-small, --disable-management
 and --disable-pkcs11

 Also changed MANAGEMENT_ENABLED to ENABLE_MANAGEMENT from the original
 patch.
]

Mailing-list: http://thread.gmane.org/gmane.network.openvpn.devel/4639
Signed-off-by: Matthew L. Creech <mlcreech@gmail.com>
Acked-by: Gert Doering <gert@greenie.muc.de>
Signed-off-by: David Sommerseth <davids@redhat.com>